Ec=4;
Em=2;
fm=700;
fc=7000;
wc=2*pi*fc;
wm=2*pi*fm;
t=0:10e-7:0.5*10e-3;
m=Em/Ec;
ec=Ec*(cos(wc*t));
em=Em*(cos(wm*t));
eam=Ec.*(1+m.*cos(wm.*t)).*cos(wc.*t);
subplot(3,2,1);
plot(t,eam);
xlabel('frequency');
ylabel('amplitude');
title('Modulated Signal m<1');
 
subplot(3,2,2);
stem(fc,Ec);
hold on;
k=m.*Ec./2;
stem((fc+fm),k);
hold on;
stem((fc-fm),k);
xlabel('frequency');
ylabel('amplitude');
title('Modulated Signal m<1');
 
Ec=4;
Em=4;
fm=700;
fc=7e3;
wc=2*pi*fc;
wm=2*pi*fm;
t=0:10e-7:0.5*10e-3;
m=Em/Ec;
ec=Ec*(cos(wc*t));
em=Em*(cos(wm*t));
eam=Ec.*(1+m.*cos(wm.*t)).*cos(wc.*t);
subplot(3,2,3);
plot(t,eam);
xlabel('frequency');
ylabel('amplitude');
title('Modulated Signal m=1');
 
subplot(3,2,4);
stem(fc,Ec);
hold on;
k=m.*Ec./2;
stem((fc+fm),k);
hold on;
stem((fc-fm),k);
xlabel('frequency');
ylabel('amplitude');
title('Modulated Signal m=1');
 
Ec=2;
Em=4;
fm=700;
fc=7e3;
wc=2*pi*fc;
wm=2*pi*fm;
t=0:10e-7:0.5*10e-3;
m=Em/Ec;
ec=Ec*(cos(wc*t));
em=Em*(cos(wm*t));
eam=Ec.*(1+m.*cos(wm.*t)).*cos(wc.*t);
subplot(3,2,5);
plot(t,eam);
xlabel('frequency');
ylabel('amplitude');
title('Modulated Signal m>1');
 
subplot(3,2,6);
stem(fc,Ec);
hold on;
k=m.*Ec./2;
stem((fc+fm),k);
hold on;
stem((fc-fm),k);
xlabel('frequency');
ylabel('amplitude');
title('Modulated Signal m>1');
