        mov dptr,#2500h
        movx a,@dptr
        mov b,#64h
        div ab
        mov r2,a
        mov a,b
        mov b,#0ah
        div ab
        mov r1,a
        mov r0,b
        mov a,r0
        inc dptr
        movx @dptr,a
        inc dptr
        mov a,r1
        movx @dptr,a
        inc dptr
        mov a,r2
        movx @dptr,a  
here:   sjmp here